### ISSUE TITLE
Fails to build with boost 1.66+

### ISSUE THREAD

**Issue by RedDwarf69** [mabrarov/asio_samples#111]
boost::asio::signal_set_service did disappear from boost 1.66. So asio_samples fails to build with

```
[ 71%] Building CXX object examples/ma_async_basics/CMakeFiles/ma_async_basics.dir/src/main.cpp.o
In file included from /home/reddwarf/tmp/asio_samples/libs/ma_console_close_signal/include/ma/console_close_signal.hpp:19,
                 from /home/reddwarf/tmp/asio_samples/libs/ma_console_close_signal/include/ma/console_close_guard.hpp:20,
                 from /home/reddwarf/tmp/asio_samples/examples/ma_async_basics/src/main.cpp:22:
/home/reddwarf/tmp/asio_samples/libs/ma_console_close_signal/include/ma/console_close_signal_service.hpp:40:24: error: ‘signal_set_service’ in namespace ‘boost::asio’ does not name a type
   typedef boost::asio::signal_set_service     service_impl_type;
```

when using it.

**Comment by mabrarov** [comment]
This is known issue which was fixed in pull request #107. Could you please check if this issue is still actual on develop branch?

**Comment by mabrarov** [comment]
Issue was fixed - changes were merged into develop branch and will be merged into master branch with the nearest release (going to be released within ~1 week from the date of this message).

Build with Boost 1.67.0 was added into automated build matrix:

1. [On Ubuntu 14.04](https://github.com/mabrarov/asio_samples/blob/2017a9ab92e61f1928e14a0211a4422a56f35593/.travis.yml#L30)
1. [On Windows](https://github.com/mabrarov/asio_samples/blob/db94e8fcd3e14944da5682f368c92c07be8f94f6/.appveyor.yml#L29)
